FROM python:3.10-alpine

LABEL maintainer="foo@bar.com"
ARG TZ='Asia/Shanghai'

ARG CHATGPT_ON_WECHAT_VER

ENV BUILD_PREFIX=/app

RUN sed -i 's/https:\/\/dl-cdn.alpinelinux.org/https:\/\/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache \
        bash \
        curl \
        wget \
        git \
    && git config --global http.proxy http://192.168.192.128:7890 \
    && git clone --depth 1 https://github.com/kinboyw/chatgpt-on-wechat.git ${BUILD_PREFIX}\
    && cd ${BUILD_PREFIX} \
    && cp config-template.json ${BUILD_PREFIX}/config.json \
    && /usr/local/bin/python -m pip install --no-cache --upgrade pip \
    #&& pip config set global.index-url 'https://pypi.tuna.tsinghua.edu.cn/simple' \
    #&& pip config set install.trusted-host 'https://pypi.tuna.tsinghua.edu.cn' \
    && pip install  --no-cache -r requirements.txt \
    && pip install  --no-cache -r requirements-optional.txt \
    && apk del curl wget git

WORKDIR ${BUILD_PREFIX}

ADD ./entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh \
    && adduser -D -h /home/noroot -u 1000 -s /bin/bash noroot \
    && chown -R noroot:noroot ${BUILD_PREFIX}

USER noroot

ENTRYPOINT ["/entrypoint.sh"]
